language: ruby
rvm:
- 2.1.1
install: bin/wad
script:
- bundle exec rake spec
env:
  global:
  - S3_BUCKET_NAME=tmcyf-bundler
  - S3_REGION=us-east-1
  - secure: HmzBdsU38LNGGlkAtPlQAww1CS4gQC737mu/RG+DmcvC0FiUTKN/x42+1ErADGMC5pHuww47xbG31oOmONMw46thBwAIMjPM7hKRSKcV5MHQU4F/WbvR6cNrYXOPpO5+FJrg0k55Fc33u2tS+PURGHPR+UYXt1MM0J7lsYJFKuU=
  - secure: VoU7q0L9gbPW74GqsMxiZGzfis7UYfmIOm78IJweE1cxz5qEz2ybR0DSLHG4BjBolJy3N8+PttXetvAaUjXktWjcDEvNT5JnSfN68CMohAmDnlHVeth4mpofasguyHQQaL3kOSviV5KQ4ysUR79Oc4Ss27gLh0zTK3ZRMfvooco=
  - secure: UA+TLAHwumbf5aRcjdvi+uP+9Yr6jwSgZmC/FFSpb/+pqkLi+539Cb4BqY1abnixZ7BBRemka/ddECXXauwPAcks2M1Z2cpV0k2EMkzB1wSjhGszBN/3HXqixps/toYv4YBhZcOJN/2Snk7DSBjDKrmaaBZKv1fNryuzG7qnF4k=
