language: ruby
rvm:
  - 2.0.0-p451
  - 2.1.1
install: bin/wad
script:
- bundle exec rake db:create db:migrate
- bundle exec rake spec
env:
  global:
  - S3_BUCKET_NAME=tmcyf-bundler
  - S3_REGION=us-east-1
  - secure: boGUx33LP3xvzd+hFdT2tvr8+F7pv1b+t0MMc7PdGOi4oM3+RiuFRYPqS5PJj2NbduYC7fXiLQlcnCJz/M17qK1zf3BYcBPaaYP5cbgfSNOVJ6G6XiEvPXFmWlA8Vt2kZ3LCtWXoOE931V44Ausnirg/bkLo2o4OZtJHDCrxIvY= # S3_CREDENTIALS
  - secure: VoU7q0L9gbPW74GqsMxiZGzfis7UYfmIOm78IJweE1cxz5qEz2ybR0DSLHG4BjBolJy3N8+PttXetvAaUjXktWjcDEvNT5JnSfN68CMohAmDnlHVeth4mpofasguyHQQaL3kOSviV5KQ4ysUR79Oc4Ss27gLh0zTK3ZRMfvooco= # MAILCHIMP_CAMPAIGN_ID
  - secure: ahwZo0Do8OJG+tovbqATMpoDA2gJ+XKyaejw1yUccythcnD7/8O9noqyhfWUad7lHK3nbDxrLDkzeEbsVTLWqCzy+3BVvLY98GMux/sKF9Rc8qVZnhtnAa71/MikkS8JFPzugIJnvCRjYbKP5cdxo5GQUStxBtOY7E87x8BPUrc= # MAILCHIMP_API_KEY
  - secure: Jtd2rGsVD5j/UoA187Ck0/garVPl5RKBmJ3mqxbqI4hR6Ynh6oIkHIaa4d+3FkJUJQHeDH4eqK651ayswbCIdWPJmrLxVAH4grBSCRyiL+VE4RG40AIndCqbQulERR8q8lhpUuK0CJtuITO/l3ULJNKIeKP1yoovrm7JZzo+/9I= # AWS_ACCESS_KEY
  - secure: XzheLFfJCXNnHlyw3ZndjclXrn+PP1VmI7QriYk669lxfcI8Xru1xyUzoOiW5rSB4Ivk40oH75dZpTapmaogQnT9/ya9IO3i/GAbV8yRZeTtQJ4B6BTW1dvp7wwDtjQUCqrVbjshb8A+Zpi/+VVcFI8Fe/ZsaY2oEpXomErEY/E= # AWS_SECRET_KEY
