language: ruby
rvm:
  - 2.1.1
  - 2.2.4
install: bin/wad
script:
- bundle exec rake db:create db:migrate
- bundle exec rake spec
env:
  global:
  - S3_BUCKET_NAME=tmcyf-bundler
  - S3_REGION=us-east-1
  - secure: A/0Qngk17Hgh9z5C++/wanU8+/ovIHQgIOwJsHHp+D032hBNX9sHgFzHKprlx/zutL/HBaXE4KGMTnn+ZJ1xnMLf5KC6JL77LWLnqZzDrF6+fXXc6aHA+mH308eq3T6rn/WTsPlF0QnkOYH5rqqpy9nPl9KM5y441QN0JOVYuqM= # S3_CREDENTIALS
  - secure: VoU7q0L9gbPW74GqsMxiZGzfis7UYfmIOm78IJweE1cxz5qEz2ybR0DSLHG4BjBolJy3N8+PttXetvAaUjXktWjcDEvNT5JnSfN68CMohAmDnlHVeth4mpofasguyHQQaL3kOSviV5KQ4ysUR79Oc4Ss27gLh0zTK3ZRMfvooco= # MAILCHIMP_CAMPAIGN_ID
  - secure: ahwZo0Do8OJG+tovbqATMpoDA2gJ+XKyaejw1yUccythcnD7/8O9noqyhfWUad7lHK3nbDxrLDkzeEbsVTLWqCzy+3BVvLY98GMux/sKF9Rc8qVZnhtnAa71/MikkS8JFPzugIJnvCRjYbKP5cdxo5GQUStxBtOY7E87x8BPUrc= # MAILCHIMP_API_KEY
  - secure: G5JN6SAcBm2X5j3oONB40PjHMw36+YWmbsFRSBjf7yzxxxZXy7+cu3ewfU7iDjp5L6WjoUqBXFCwVvRFkBAO0n0vKmec2xUWibmfzuWnZfpvyMmEW9wclFZ2eldbvQqxyoTgJMw8l+euCFH1bphPx3cgzWtocGCLhrbPjK2Rjl4= # AWS_ACCESS_KEY
  - secure: Hvrgr0vBxGpSK5QRZcCtfW1Pgp5ucLLolJPs07cLqYyK9RYb3NRr8msXl91WDqenwgIiTAPEVexaxgmI6ApX6ZflC2lyeI2LJEQiVr05tndknSKFTUkzlXKrXSds+7VRxlxCOo25pMAznXuAQLwIJq/+DNTGr4ZsfVY0EPm/c90= # AWS_SECRET_KEY

# Testing: 20170207-1222