development:
  adapter: postgresql
  database: tmcyf_helios
  user: tmcyf
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
  pool: 5
  timeout: 5000