development:
  adapter: postgresql
  database: db_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: db_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db_production
  pool: 5
  timeout: 5000