require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetreatsController do

  # This should return the minimal set of attributes required to create a valid
  # Retreat. As you add validations to Retreat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetreatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all retreats as @retreats" do
      retreat = Retreat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retreats).should eq([retreat])
    end
  end

  describe "GET show" do
    it "assigns the requested retreat as @retreat" do
      retreat = Retreat.create! valid_attributes
      get :show, {:id => retreat.to_param}, valid_session
      assigns(:retreat).should eq(retreat)
    end
  end

  describe "GET new" do
    it "assigns a new retreat as @retreat" do
      get :new, {}, valid_session
      assigns(:retreat).should be_a_new(Retreat)
    end
  end

  describe "POST register" do
    describe "with valid params" do
      it "creates a new Registration" do
        expect {
          post :register, {:retreat => valid_attributes}, valid_session
        }.to change(Retreat, :count).by(1)
      end

      it "assigns a newly created retreat as @retreat" do
        post :create, {:retreat => valid_attributes}, valid_session
        assigns(:retreat).should be_a(Retreat)
        assigns(:retreat).should be_persisted
      end

      it "redirects to the created retreat" do
        post :create, {:retreat => valid_attributes}, valid_session
        response.should redirect_to(Retreat.last)
      end
    end
  end


  # TODO: WTFFFFF
  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retreat" do
        expect {
          post :create, {:retreat_registration => valid_attributes}, valid_session
        }.to change(RetreatRegistration, :count).by(1)
      end

      it "assigns a newly created retreat as @retreat" do
        post :create, {:retreat => valid_attributes}, valid_session
        assigns(:retreat_registration).should be_a(RetreatRegistration)
        assigns(:retreat_registration).should be_persisted
      end

      it "redirects to the created retreat" do
        post :create, {:retreat => valid_attributes}, valid_session
        response.should redirect_to(Retreat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved retreat as @retreat" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retreat.any_instance.stub(:save).and_return(false)
        post :create, {:retreat => {  }}, valid_session
        assigns(:retreat).should be_a_new(Retreat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retreat.any_instance.stub(:save).and_return(false)
        post :create, {:retreat => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested retreat" do
        retreat = Retreat.create! valid_attributes
        # Assuming there are no other retreats in the database, this
        # specifies that the Retreat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retreat.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => retreat.to_param, :retreat => { "these" => "params" }}, valid_session
      end

      it "assigns the requested retreat as @retreat" do
        retreat = Retreat.create! valid_attributes
        put :update, {:id => retreat.to_param, :retreat => valid_attributes}, valid_session
        assigns(:retreat).should eq(retreat)
      end

      it "redirects to the retreat" do
        retreat = Retreat.create! valid_attributes
        put :update, {:id => retreat.to_param, :retreat => valid_attributes}, valid_session
        response.should redirect_to(retreat)
      end
    end

    describe "with invalid params" do
      it "assigns the retreat as @retreat" do
        retreat = Retreat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retreat.any_instance.stub(:save).and_return(false)
        put :update, {:id => retreat.to_param, :retreat => {  }}, valid_session
        assigns(:retreat).should eq(retreat)
      end

      it "re-renders the 'edit' template" do
        retreat = Retreat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retreat.any_instance.stub(:save).and_return(false)
        put :update, {:id => retreat.to_param, :retreat => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested retreat" do
      retreat = Retreat.create! valid_attributes
      expect {
        delete :destroy, {:id => retreat.to_param}, valid_session
      }.to change(Retreat, :count).by(-1)
    end

    it "redirects to the retreats list" do
      retreat = Retreat.create! valid_attributes
      delete :destroy, {:id => retreat.to_param}, valid_session
      response.should redirect_to(retreats_url)
    end
  end

end
