---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: fawkes
  domain: tmcyf.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_toolss
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  instance_id: i-dbfdcdfa
  image_type: m1.small
  image_id: ami-0b9c9f62
  security_groups:
  - tmcyf_production_default
  - tmcyf_production_web
  - tmcyf_production_fawkes
  - tmcyf_production_app
  - tmcyf_production_unicorn
  - tmcyf_production_nginx
  - tmcyf_production_common
  - tmcyf_production_collectd
  - tmcyf_production_monit
  - tmcyf_production_web_tools
  external_host: ec2-54-81-165-103.compute-1.amazonaws.com
  external_ip: 54.81.165.103
  internal_host: ip-10-165-12-67.ec2.internal
  internal_ip: 10.165.12.67
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
