---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: tartarus
  domain: tmcyf.org
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-4e2f952b
  image_type: t1.micro
  image_id: ami-23d9a94a
  security_groups:
  - tmcyf_production_default
  - tmcyf_production_web
  - tmcyf_production_web_tools
  - tmcyf_production_tartarus
  - tmcyf_production_app
  - tmcyf_production_unicorn
  - tmcyf_production_nginx
  - tmcyf_production_collectd
  - tmcyf_production_common
  - tmcyf_production_monit
  - tmcyf_production_db
  - tmcyf_production_postgresql
  - tmcyf_production_postgresql_master
  - tmcyf_production_examples
  - tmcyf_production_graphite_server
  - tmcyf_production_graphite_web
  external_host: ec2-184-73-116-177.compute-1.amazonaws.com
  external_ip: 184.73.116.177
  internal_host: ip-10-203-3-147.ec2.internal
  internal_ip: 10.203.3.147
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
